### ISSUE TITLE
Domanda: Repo di altro dipartimento

### ISSUE THREAD

**Issue by dennisangemi** [UNICT-DMI/.github#4]
Buonasera! Questo sicuramente non è il "posto" più adatto per porre la domanda che segue e mi scuso. Sto realizzando un sito web in mkdocs (SSG) per raccogliere i compiti scritti di Fisica Generale 1 (DFA) che per adesso è [qui](https://github.com/dennisangemi/DFA-compiti). Mi piacerebbe trasferire il repo altrove: l'ideale sarebbe una github organization gestita dal DFA ma non credo esista quindi mi rivolgo a voi per capire se potesse essere una buona idea quella di ospitare il progetto qui (ho visto che sono presenti progetti che non riguardano strettamente il DMI). 

Grazie! ;)

**Comment by Helias** [comment]
Buonasera!

Certo che puoi spostare o creare una repository qui, l'organizzazione è nata per ospitare i progetti open source che mirano a migliorare la didattica e l'ambiente in tutto l'Ateneo.
 
Appena posso ti aggiungo all'organizzazione in modo che puoi creare una repository.

Sei il benvenuto, se ti serve una mano chiedi pure nel gruppo telegram~~, inoltre, ti consiglierei di sfruttare le GitHub Pages se non lo stai già facendo~~, ho visto che lo stai già facendo, ottimo 👍

**Comment by dennisangemi** [comment]
@Helias Buonasera a tutti e tutte! Grazie mille
